
console.log("Hello")
console.log("Hello")
console.log("Hello")
console.log("Hello")
console.log("Hello")
console.log("Hello")
console.log("Hello")
console.log(a/0)
console.log("Hello")
console.log("Hello")
console.log("Hello")
console.log("Hello")
